version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: debug-redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
    volumes:
      - redis_data:/data
    command: >
      redis-server
      --appendonly yes
      --requirepass ${REDIS_PASSWORD:-}
      --loglevel debug
    networks:
      - debug-net

volumes:
  redis_data:

networks:
  debug-net:
    driver: bridge