services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: [ "/bin/sh", "-c", "./main -m=${IN_MEMORY_STORAGE}" ]
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    profiles:
      - app
    restart: unless-stopped

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: ozonuser
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: ozondb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    profiles:
      - postgres

  redis:
    image: redis:7
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    env_file:
      - .env
    profiles:
      - redis

volumes:
  pgdata:
